model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"

[features]
web_search_request = true
unified_exec = true
steer = true
collab = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

# [mcp_servers.openaiDeveloperDocs]
# url = "https://developers.openai.com/mcp"
