model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"

[features]
web_search_request = true
unified_exec = true
steer = true
collab = true
collaboration_modes = true

[tui]
experimental_mode = "execute"

# [mcp_servers.openaiDeveloperDocs]
# url = "https://developers.openai.com/mcp"
