model = "gpt-5.1-codex"
model_reasoning_effort = "medium"
[projects."/Users/tk/workspace/art/openai-agents"]
trust_level = "trusted"

[projects."/Users/tk/workspace/tk/pragma"]
trust_level = "trusted"

[projects."/Users/tk/workspace/tk/graphite"]
trust_level = "trusted"

[projects."/Users/tk/Downloads"]
trust_level = "trusted"

[projects."/Users/tk/workspace/art/hopper"]
trust_level = "trusted"

[projects."/Users/tk/workspace/art/seed"]
trust_level = "trusted"

[notice]
hide_gpt5_1_migration_prompt = true
hide_rate_limit_model_nudge = true

[feature]
web_search_request = true

[profiles.yolo]
approval_policy = "never"
sandbox_mode    = "danger-full-access"
