model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"

[features]
web_search_request = true
rmcp_client = true

[notice]
hide_gpt5_1_migration_prompt = true
hide_rate_limit_model_nudge = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

# [mcp_servers.chrome-devtools]
# command = "npx"
# args = ["chrome-devtools-mcp@latest"]
